### ISSUE TITLE
Similar sequence name in target enrichment probe file

### ISSUE THREAD

**Issue by christec5** [V-Z/sondovac#4]
Hello, 
Thank you for providing this set of scripts. I would like to use it with my own data. I did several test and until now I got the pipeline to run until the end very easily.
I have several few questions maybe very simple but I guess you might have the answer.

1. In my final file (output_target_enrichment_probe_sequence file), I realize that many sequences have similar sequence name but are different. Is it normal ? 
2. It is said that the advantage to use Geneious is to get the exon-intron boundaries. I can see each contig but I don't see where I could see this information about the boundary. 

Thank a lot.

**Comment by rschmickl** [comment]
I apologize for not responding earlier.

1. Your final file contains exonic sequences that are part of a gene. Meaning that your final sequence names have a first part that can be identical, as it is the same unique identifier of the same gene (the unique identifiers were created based on the transcriptome file that was one of the input files of Sondovac part A), followed by a second part, which is the label of the particular exon of this gene (e.g., "contig_3"). That the exons are indicated with the term "contig" comes from the de novo assembly step in Geneious. Once you build a phylogeny from these enriched sequences, you will concatenate all exons of a gene to one locus.

2. I do not know where I stated that this is an advantage of Geneious. It is an advantage of the probe design with an approach such as Sondovac: As you design probes based on a comparison of transcriptome with genome skim data, you select exonic regions only. Once you do target enrichment of these sequences, non-coding (mainly intronic) flanking regions will also be enriched to some degree, and you can build phylogenies based on coding and non-coding regions.
