### ISSUE TITLE
Combining paired-end reads failed

### ISSUE THREAD

**Issue by Fengyaa** [V-Z/sondovac#5]
Hi, I downloaded software from https://github.com/V-Z/sondovac.git and sample_data-2.0. When I ran this pipeline like this:
 ../sondovac_part_a.sh -n -f input1_JHCN_Oxalis_corniculata_1168transcripts.fa -c input2_Ricinus_communis_reference_plastid_genome.fsa -m input5_Ricinus_communis_reference_mitochondrial_genome.fasta -t input3_J12_Oxalis_obtusa_genome_skim_data_R1.fastq -q input4_J12_Oxalis_obtusa_genome_skim_data_R2.fastq

I got the error:

Step 4 of the pipeline - combination of paired-end reads.

Combining paired-end reads

[FLASH] ERROR: Failed to open ".//home/biosys/fy/software/sondovac-master/sample_data/output_combined_reads_no_cp_no_mt_reads.extendedFrags.fastq" for writing: No such file or directory
[FLASH] FLASH did not complete successfully; exiting with failure status (1)

Error! Combining paired-end reads failed. Aborting. Check if files
input5_Ricinus_communis_reference_mitochondrial_genome_non-interleaved.fasta, /home/biosys/fy/software/sondovac-master/sample_data/output_genome_skim_data_no_cp_no_mt_reads.1.fq and /home/biosys/fy/software/sondovac-master/sample_data/output_genome_skim_data_no_cp_no_mt_reads.2.fq are correct.

I can't figure out what's going wrong, Could you please help me to solve this?
Thanks.

**Comment by V-Z** [comment]
Hello,
thank You for testing our development version. :-) I did recently plenty of changes in the Git and not everything is fully tested yet, so there might be issues. Obviously there are. Released version 1.2 should work well, but I'm going to release significantly enhanced version 1.3 in one or two weeks...
To trace Your issue, could You, please, send me full path to Your working directory with Sondovač and list content of that directory? And list content of directory `/home/biosys/fy/software/sondovac-master/sample_data`? Do You have write permission there?

**Comment by Fengyaa** [comment]
Hi, Thank you for your response.
The full path of Sondovač is /home/biosys/fy/software/sondovac-master/, I put the sample_data which is my working directory in this directory. Here's the content of sample_data after I ran this pipeline 
![image](https://user-images.githubusercontent.com/31508684/33638576-cf6fac58-da61-11e7-97c8-14a5c94d111c.png)
And yes, I have write permission in this directory.

**Comment by V-Z** [comment]
OK thank You. I suppose directory `/home/biosys/fy/software/sondovac-master/sample_data/` contains also the Sondovač scripts, so that everything is in one directory. The problem is with `.//home/biosys/fy/software/sondovac-master/sample_data/output_combined_reads_no_cp_no_mt_reads.extendedFrags.fastq`, which is invalid path. I'm investigating how it got generated there, as `realpath` command should sanitize everything.

**Comment by V-Z** [comment]
It was issue with FLASh, which for some reason always appends `./` to the beginning of the output file path. It should be fixed in commit 9e3fa86302386f8770b8abdf84e5fbf75092143c. Please, update, try it and report if it works.

**Comment by Fengyaa** [comment]
It works. Thank you very much!
