### ISSUE TITLE
Possibility of using single-end GSS reads

### ISSUE THREAD

**Issue by coyotree** [V-Z/sondovac#6]
Hello,
I'm very interested in this pipeline but it appears there is not a single-end GSS read option. Unfortunately, the only data available to me is single-end. Would you know of a way to incorporate this data into this particular workflow?
Thanks for any advice.
Sincerely,
Cody

**Comment by V-Z** [comment]
Hello,
we were thinking about this option, but we decided not to do it as it has certain issues, especially possible lower quality of the probes. Such modification was made in the fork https://github.com/uribe-convers/sondovac and commented in https://uribeconvers.wordpress.com/2016/05/11/capture-probe-design-with-sondovac/ You can start by exploring Simon's modifications.

**Comment by rschmickl** [comment]
Indeed, it looks like people exclude the step of combining paired-end reads with FLASH when they want to use Sondovac with single-end reads (see Simon's nicely commented code). However, the subsequent de novo assembly of the genome skim reads might suffer quite a lot from assembling non-combined, shorter reads. Especially the low sequencing depth might be an issue, and also the general shortage of the probe sequences, which will then not pass the minimum length filtering steps later on. Hence, only in case you have a high quantity of high quality single-end reads of longer length (i.e., 250 bp, 300 bp), you could give Simon's modifications a try.

**Comment by V-Z** [comment]
I'm closing it, but if You have any other issues with Sondovač, contact us.
